apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: base-wordpress-cluster
  region: us-east-2

nodeGroups:
  - name: nodegroup-wordpress
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: dragon_us_east_2