apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: base-wordpress-cluster-dev
  region: us-east-1

nodeGroups:
  - name: nodegroup-wordpress-dev
    instanceType: t2.small
    desiredCapacity: 3
    ssh:
      publicKeyName: dragon