apiVersion: v1
kind: Service
metadata:
  name: wordpress-mysql-dev
  labels:
    app: wordpress-dev
spec:
  ports:
    - port: 3306
  selector:
    app: wordpress-dev
    tier: mysql-dev
  clusterIP: None
---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: wordpress-mysql-dev
  labels:
    app: wordpress-dev
spec:
  selector:
    matchLabels:
      app: wordpress-dev
      tier: mysql-dev
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-dev
        tier: mysql-dev
    spec:
      containers:
      - image: mysql:5.6
        name: mysql-dev
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage-dev
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage-dev
        persistentVolumeClaim:
          claimName: mysql-pv-claim-dev
